import assert from "node:assert/strict"; import { readFileSync } from "node:fs"; import test from "node:test";
import { planPreliminarySurveyGivenFixedAssignments } from "../lib/preliminary-survey-v2/reverse-planner/solver";
import { normalizePublicSampleCodes } from "../lib/preliminary-survey-v2/reverse-planner/public-sample-code";
import { PRELIMINARY_SURVEY_CANONICAL_SHA, REVERSE_PLANNER_VERSION, type PlanningSnapshot } from "../lib/preliminary-survey-v2/reverse-planner/types";
import { candidateDates } from "../lib/preliminary-survey-v2/reverse-planner/candidate-dates";
const users = [{ id: 1, name: "강종구", active: true, experienced: true, baseCode: "C" }, { id: 2, name: "이태환", active: true, experienced: false, baseCode: "A" }, { id: 3, name: "고유빈", active: true, experienced: true, baseCode: "F" }];
function fixture(): PlanningSnapshot { return { canonicalSha: PRELIMINARY_SURVEY_CANONICAL_SHA, plannerVersion: REVERSE_PLANNER_VERSION,
  users, scheduleBlocks: [], routeEvidence: [], writingCounters: {}, targets: [{ id: 10, code: "H0527", name: "전환 회귀", address: "대전 A", businessType: "existing",
    days: [{ date: "2026-09-16", collaboratorUserIds: [2], reportWriterUserId: 2 }], fixedAssignments: [{ targetId: 10, measurementDate: "2026-09-16", assigneeUserId: 1, confirmedAt: "2026-09-01T00:00:00Z", updatedAt: "2026-09-01T00:00:00Z" }], existingPlan: null }] }; }
test("기존 assignment는 fixed confirmation으로 승격하지 않는다", () => { const input = fixture(); input.targets[0].fixedAssignments = [];
  input.targets[0].existingPlan = { id: "old", preliminaryDate: "2026-08-20", surveyMethod: "phone", participantUserIds: [1], responsibleUserId: 1, reviewerUserId: null, protected: false, updatedAt: "x", assignments: [{ measurementDate: "2026-09-15", assigneeUserId: 1, surveyCode: "C", publicSampleCode: null }] };
  const result = planPreliminarySurveyGivenFixedAssignments(input).results[0]; assert.equal(result.decision, "MANUAL_REQUIRED"); assert.equal(result.reason, "FIXED_ASSIGNEE_NOT_CONFIRMED"); });
test("planner는 고정 측정자를 변경하지 않는다", () => { const result = planPreliminarySurveyGivenFixedAssignments(fixture()).results[0]; assert.equal(result.decision, "AUTO_ASSIGNED"); assert.equal(result.fixedAssignments[0].assigneeUserId, 1); assert.ok(result.candidate?.participantUserIds.includes(2)); });
test("다일 fixed assignee는 날짜별 독립이다", () => { const input = fixture(); input.targets[0].days.push({ date: "2026-09-17", collaboratorUserIds: [3], reportWriterUserId: 3 }); input.targets[0].fixedAssignments.push({ targetId: 10, measurementDate: "2026-09-17", assigneeUserId: 3, confirmedAt: "x", updatedAt: "x" }); assert.deepEqual(planPreliminarySurveyGivenFixedAssignments(input).results[0].fixedAssignments.map((item) => [item.measurementDate, item.assigneeUserId]), [["2026-09-16", 1], ["2026-09-17", 3]]); });
test("C/CC/CCC는 natural sort이며 permutation 불변이다", () => { const input = fixture(); input.targets = ["H0010", "H0002", "H0001"].map((code, index) => ({ ...input.targets[0], id: index + 1, code, fixedAssignments: [{ ...input.targets[0].fixedAssignments[0], targetId: index + 1 }] })); const left = normalizePublicSampleCodes({ targets: input.targets, users }); const right = normalizePublicSampleCodes({ targets: [...input.targets].reverse(), users: [...users].reverse() }); assert.deepEqual(left, right); assert.deepEqual(left.map((item) => [item.businessCode, item.publicSampleCode]), [["H0001", "C"], ["H0002", "CC"], ["H0010", "CCC"]]); });
test("snapshot 배열 shuffle에도 fingerprint와 결과가 같다", () => { const input = fixture(); input.targets.push({ ...input.targets[0], id: 11, code: "H0508", fixedAssignments: [{ ...input.targets[0].fixedAssignments[0], targetId: 11, assigneeUserId: 3 }] }); const left = planPreliminarySurveyGivenFixedAssignments(input); const right = planPreliminarySurveyGivenFixedAssignments({ ...input, targets: [...input.targets].reverse(), users: [...input.users].reverse() }); assert.equal(left.sourceFingerprint, right.sourceFingerprint); assert.deepEqual(left.results, right.results); });
test("최초실시는 working day -3...-20과 방문만 사용한다", () => { const input = fixture(); input.targets[0].businessType = "first_measurement"; const dates = candidateDates("2026-09-16", "first_measurement"); assert.equal(dates.primary.length, 18); assert.equal(dates.fallback.length, 0); const result = planPreliminarySurveyGivenFixedAssignments(input).results[0]; assert.equal(result.candidate?.surveyMethod, "field"); assert.ok(dates.primary.includes(result.candidate?.preliminaryDate ?? "")); });
test("경력+비경력은 비경력자가 작성자/responsible, 경력자가 reviewer다", () => { const result = planPreliminarySurveyGivenFixedAssignments(fixture()).results[0]; assert.equal(result.candidate?.responsibleUserId, 2); assert.equal(result.candidate?.writerUserId, 2); assert.equal(result.candidate?.reviewerUserId, 1); });
test("정상 기존 plan과 fixed가 일치하면 KEEP_EXISTING이다", () => { const input = fixture(); const date = candidateDates("2026-09-16", "existing").primary[0]; input.targets[0].existingPlan = { id: "plan", preliminaryDate: date, surveyMethod: "phone", participantUserIds: [1], responsibleUserId: 1, reviewerUserId: null, protected: false, updatedAt: "x", assignments: [{ measurementDate: "2026-09-16", assigneeUserId: 1, surveyCode: "C", publicSampleCode: null }] }; assert.equal(planPreliminarySurveyGivenFixedAssignments(input).results[0].mutation, "KEEP_EXISTING"); });
test("같은 실제 측정일·같은 팀의 이동 근거가 없으면 관련 대상만 route required다", () => { const input = fixture(); input.targets.push({ ...input.targets[0], id: 11, code: "H0050", fixedAssignments: [{ ...input.targets[0].fixedAssignments[0], targetId: 11, assigneeUserId: 3 }] }); const results = planPreliminarySurveyGivenFixedAssignments(input).results; assert.ok(results.every((result) => result.reason === "ROUTE_EVIDENCE_REQUIRED")); });
test("Preview 원천 역할·fixed·route 변경은 fingerprint를 바꾼다", () => { const base = fixture(); const first = planPreliminarySurveyGivenFixedAssignments(base).sourceFingerprint; const changed = fixture(); changed.targets[0].days[0].reportWriterUserId = 3; assert.notEqual(planPreliminarySurveyGivenFixedAssignments(changed).sourceFingerprint, first); const fixed = fixture(); fixed.targets[0].fixedAssignments[0].assigneeUserId = 3; assert.notEqual(planPreliminarySurveyGivenFixedAssignments(fixed).sourceFingerprint, first); const route = fixture(); route.routeEvidence.push({ date: "2026-09-01", leftTargetId: 10, rightTargetId: 11, sameAddress: false, durationMinutes: 20, provider: "vehicle", capturedAt: "x" }); assert.notEqual(planPreliminarySurveyGivenFixedAssignments(route).sourceFingerprint, first); });
test("Canonical 조합은 있으나 일정이 모두 막히면 NO_VALID_PRELIMINARY_DATE다", () => { const input = fixture(); input.scheduleBlocks = users.map((user) => ({ userId: user.id, startDate: "2026-08-01", endDate: "2026-09-30" })); const result = planPreliminarySurveyGivenFixedAssignments(input).results[0]; assert.equal(result.reason, "NO_VALID_PRELIMINARY_DATE"); });
test("팀 일정을 만족할 수 없고 비팀 대체안만 가능하면 mismatch 수동검토다", () => { const input = fixture(); input.scheduleBlocks = [1, 2].map((userId) => ({ userId, startDate: "2026-08-01", endDate: "2026-09-30" })); const result = planPreliminarySurveyGivenFixedAssignments(input).results[0]; assert.equal(result.reason, "ONLY_MISMATCH_ALTERNATIVES_AVAILABLE"); assert.equal(result.mutation, "NONE"); });
test("보호 plan과 같은 날짜·담당자 code 그룹은 자동 재정규화하지 않는다", () => { const input = fixture(); const date = candidateDates("2026-09-16", "existing").primary[0]; input.targets[0].existingPlan = { id: "protected", preliminaryDate: date, surveyMethod: "phone", participantUserIds: [1], responsibleUserId: 1, reviewerUserId: null, protected: true, updatedAt: "x", assignments: [{ measurementDate: "2026-09-16", assigneeUserId: 1, surveyCode: "C", publicSampleCode: "C" }] }; input.targets.push({ ...input.targets[0], id: 11, code: "H0528", existingPlan: null, fixedAssignments: [{ ...input.targets[0].fixedAssignments[0], targetId: 11 }] }); const added = planPreliminarySurveyGivenFixedAssignments(input).results.find((result) => result.targetId === 11)!; assert.equal(added.reason, "PROTECTED_PLAN_REQUIRES_REVIEW"); assert.equal(added.mutation, "NONE"); });
test("migration은 additive·service-only·원자 Apply·append-only audit 계약을 고정한다", () => { const base = readFileSync("supabase/migrations/20260901160253_add_fixed_assignee_reverse_planner_v1.sql", "utf8"); const harden = readFileSync("supabase/migrations/20260902091100_harden_reverse_planner_audit.sql", "utf8"); assert.match(base, /ADD COLUMN IF NOT EXISTS public_sample_code/); assert.match(base, /CREATE TABLE IF NOT EXISTS public\.preliminary_survey_v2_fixed_assignments/); assert.match(base, /CREATE TABLE IF NOT EXISTS public\.preliminary_survey_v2_planner_audit/); assert.match(base, /SECURITY DEFINER SET search_path = ''/); assert.match(base, /REVOKE ALL ON FUNCTION[\s\S]*FROM PUBLIC, anon, authenticated, service_role/); assert.match(base, /apply_preliminary_survey_v2_reverse_planner/); assert.doesNotMatch(base, /UPDATE public\.measurement_target_business[\s\S]*WHERE.*2026-08/i); assert.match(harden, /BEFORE UPDATE OR DELETE/); assert.match(harden, /PLANNER_AUDIT_APPEND_ONLY/); });
test("선택일 batch는 단일일과 daily_staff 날짜를 모두 검색하고 사업장 전체 기간으로 확장한다", () => { const route = readFileSync("app/api/preliminary-survey-v2/reverse-planner/route.ts", "utf8"); assert.match(route, /measurementDayFormsFrom\(\{/); assert.match(route, /\.some\(\(day\) => day\.date === measurementDate\)/); assert.match(route, /buildPlanningSnapshot\(\{/); });
