-- 기존 테이블 삭제 (주의: 데이터 유실 가능)
-- DROP TABLE IF EXISTS measurement_target_business;

-- 새 테이블 생성 (Snapshot 모델) - 이미 존재하는 경우 무시됨
CREATE TABLE IF NOT EXISTS measurement_target_business (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- 식별자
  year INTEGER NOT NULL,
  period TEXT NOT NULL, -- '상반기', '하반기'
  code TEXT NOT NULL,
  
  -- 상태 및 관리 정보
  is_registered TEXT DEFAULT '미실시', -- '실시', '미실시', '거래종료'
  management_status TEXT, -- (호환성 유지용, 점차 제거)
  
  -- 국고지원 관련
  national_support_status TEXT, -- 국고결과
  plan_manager TEXT, -- 계획담당자
  measurer_id BIGINT REFERENCES users(id), -- [NEW] 측정자 (사용자 ID 참조)
  
  -- 일정 관련
  previous_measurement_date DATE, -- 전회측정일
  previous_measurement_period TEXT, -- 전회측정주기 (문자열 or 개월수 호환)
  future_measurement_period INTEGER, -- 향후측정주기 (개월)
  
  future_measurement_date DATE, -- 금회예정일
  measurement_month TEXT, -- 측정예정월
  measurement_date DATE, -- 금회측정확정일
  
  -- 사업장 정보
  business_category TEXT,
  address TEXT,
  office_jurisdiction TEXT,
  business_name TEXT,
  
  -- 담당자 정보
  manager_name TEXT,
  manager_mobile TEXT,
  phone TEXT,
  
  notes TEXT,
  
  -- 유니크 제약
  UNIQUE(code, year, period)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_measurement_target_business_year_period ON measurement_target_business(year, period);
CREATE INDEX IF NOT EXISTS idx_measurement_target_business_code ON measurement_target_business(code);

-- [NEW] users 테이블 컬럼 추가
ALTER TABLE users ADD COLUMN IF NOT EXISTS job VARCHAR(20) DEFAULT '측정';

-- [NEW] measurement_target_business 테이블 컬럼 추가 (기존 테이블이 있는 경우)
ALTER TABLE measurement_target_business ADD COLUMN IF NOT EXISTS measurer_id BIGINT REFERENCES users(id);

-- [NEW] preliminary_survey 테이블 컬럼 추가
ALTER TABLE preliminary_survey ADD COLUMN IF NOT EXISTS notes TEXT;

-- RLS 정책 (필요 시)
ALTER TABLE measurement_target_business ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read/write for all users" ON measurement_target_business
    FOR ALL
    USING (true)
    WITH CHECK (true);
