-- Create a table to store data verification issues
create table if not exists public.data_verification_issues (
  id bigint generated by default as identity primary key,
  code text not null,
  business_name text not null,
  issue_type text not null, -- 'MISMATCH_NAME', 'MISMATCH_REPRESENTATIVE', etc.
  description text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add index for fast lookups by code
create index if not exists idx_data_verification_issues_code on public.data_verification_issues (code);

-- Enable RLS
alter table public.data_verification_issues enable row level security;

-- Create policy to allow read access for authenticated users
create policy "Allow read access for authenticated users"
  on public.data_verification_issues for select
  to authenticated
  using (true);

-- Create policy to allow all access for service role (if needed) orAuthenticated users for now to simplify
create policy "Allow all access for authenticated users"
  on public.data_verification_issues for all
  to authenticated
  using (true)
  with check (true);
