-- 관리자 예비조사 예외 정비 감사기록 + 원자적 정비 RPC
--
-- 배경: '예비조사 연결 확인 필요'(C) 14건은 초기 V2 backfill 예비조사자가 실제 측정 인력과
-- 연결되지 않은 TYPE 1 사례다. 전부 measurement_journal.sequence_number 부여 후(확정) 데이터이므로
-- 일반 수정 대신 관리자 예외 정비 경로가 필요하다.
-- 이 migration은:
--   1) 예비조사 예외 정비 감사기록 테이블 추가 (preliminary_survey_exception_log)
--   2) 관리자 전용 원자적 정비 RPC (admin_repair_preliminary_survey_connection)
-- 기존 데이터 backfill 금지. 일반 사용자 수정 경로는 건드리지 않는다.

-- ---------- 1. 감사기록 테이블 ----------
CREATE TABLE IF NOT EXISTS public.preliminary_survey_exception_log (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  measurement_target_business_id bigint NOT NULL
    REFERENCES public.measurement_target_business(id) ON DELETE CASCADE,
  code varchar(50) NOT NULL,
  old_participant_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  new_participant_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  old_participant_names jsonb NOT NULL DEFAULT '[]'::jsonb,
  new_participant_names jsonb NOT NULL DEFAULT '[]'::jsonb,
  old_link_measurer_id integer,
  new_link_measurer_id integer,
  changed_by varchar(100) NOT NULL,
  reason text NOT NULL CHECK (btrim(reason) <> ''),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_preliminary_survey_exception_log_target
  ON public.preliminary_survey_exception_log(measurement_target_business_id, created_at);

COMMENT ON TABLE public.preliminary_survey_exception_log IS
'확정(sequence_number 부여) 이후 관리자 예비조사 예외 정비 감사기록. 변경 전/후 V2 예비조사자와 예·측(link_measurer_id)을 기록한다.';
COMMENT ON COLUMN public.preliminary_survey_exception_log.reason IS
'변경 사유(필수). btrim 후 빈 값 저장 불가.';

REVOKE ALL ON TABLE public.preliminary_survey_exception_log FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.preliminary_survey_exception_log TO service_role;

-- ---------- 2. 관리자 예외 정비 RPC (원자적) ----------
-- V2 예비조사자 정정 + link_measurer_id 지정 + 감사기록 생성이 하나의 transaction으로 처리된다.
-- 한 건이라도 검증에 실패하면 전체 rollback(중간 상태 저장 없음).
DROP FUNCTION IF EXISTS public.admin_repair_preliminary_survey_connection(
  bigint, jsonb, jsonb, integer, text, text
);

CREATE OR REPLACE FUNCTION public.admin_repair_preliminary_survey_connection(
  p_target_id bigint,
  p_participant_user_ids jsonb,
  p_participant_names jsonb,
  p_link_measurer_id integer,
  p_reason text,
  p_changed_by text
) RETURNS public.preliminary_survey_v2_plans
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  target_row public.measurement_target_business;
  plan_row public.preliminary_survey_v2_plans;
  link_name text;
  staff_names text[] := ARRAY[]::text[];
  staff_extra text[] := ARRAY[]::text[];
  journal_confirmed boolean;
  v_idx integer;
  v_id integer;
  v_name text;
BEGIN
  -- 1. 변경 사유 필수
  IF p_reason IS NULL OR btrim(p_reason) = '' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'REASON_REQUIRED';
  END IF;

  -- 2. 예비조사자 목록 구조 검증 (비어있지 않고, id/name 배열 길이 일치)
  IF p_participant_user_ids IS NULL OR jsonb_typeof(p_participant_user_ids) <> 'array'
     OR p_participant_names IS NULL OR jsonb_typeof(p_participant_names) <> 'array'
     OR jsonb_array_length(p_participant_user_ids) = 0
     OR jsonb_array_length(p_participant_user_ids) <> jsonb_array_length(p_participant_names) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_PARTICIPANTS';
  END IF;

  -- 3. 대상 사업장 존재 + 행 잠금
  SELECT * INTO target_row FROM public.measurement_target_business WHERE id = p_target_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'TARGET_NOT_FOUND'; END IF;

  -- 4. V2 예비조사 계획 존재 + 행 잠금
  SELECT * INTO plan_row FROM public.preliminary_survey_v2_plans
    WHERE measurement_target_business_id = p_target_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'V2_PLAN_NOT_FOUND'; END IF;

  -- 5. 확정 상태(sequence_number 부여) 확인: 이 경로는 확정 데이터 예외 수정 전용
  SELECT EXISTS (
    SELECT 1 FROM public.measurement_journal AS journal
    WHERE journal.code = target_row.code
      AND journal.measurement_year = target_row.year
      AND btrim(journal.measurement_period) = btrim(target_row.period)
      AND journal.sequence_number IS NOT NULL
  ) INTO journal_confirmed;
  IF NOT journal_confirmed THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'SEQUENCE_NUMBER_NOT_CONFIRMED';
  END IF;

  -- 6. 예비조사자 id/name 쌍이 users와 일치하는지 검증 (임의 조작 방지)
  v_idx := 0;
  FOR v_idx IN 0 .. jsonb_array_length(p_participant_user_ids) - 1 LOOP
    v_id := (p_participant_user_ids->>v_idx)::integer;
    v_name := p_participant_names->>v_idx;
    IF NOT EXISTS (
      SELECT 1 FROM public.users AS u
      WHERE u.id = v_id AND u.name = v_name
    ) THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'PARTICIPANT_MISMATCH_AT_' || (v_idx + 1)::text;
    END IF;
  END LOOP;
  IF (SELECT COUNT(*) FROM (SELECT DISTINCT value::text AS v FROM jsonb_array_elements(p_participant_user_ids)) s)
     <> jsonb_array_length(p_participant_user_ids) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'PARTICIPANT_DUPLICATE';
  END IF;

  -- 7. 실제 측정 인원 합집합 (단일일 collaborators + 다일 daily_staff 협력자)
  SELECT COALESCE(array_agg(btrim(t)), ARRAY[]::text[]) INTO staff_names
  FROM unnest(string_to_array(COALESCE(target_row.collaborators, ''), ',')) AS t
  WHERE btrim(t) <> '';

  IF target_row.daily_staff IS NOT NULL AND jsonb_typeof(target_row.daily_staff) = 'array' THEN
    SELECT COALESCE(array_agg(DISTINCT btrim(collab)), ARRAY[]::text[]) INTO staff_extra
    FROM jsonb_array_elements(target_row.daily_staff) AS day(entry)
    CROSS JOIN LATERAL jsonb_array_elements_text(
      CASE
        WHEN jsonb_typeof(entry->'collaborators') = 'array' THEN entry->'collaborators'
        ELSE to_jsonb(string_to_array(COALESCE(entry->>'collaborators', ''), ','))
      END
    ) AS t(collab)
    WHERE btrim(collab) <> '';
    staff_names := staff_names || staff_extra;
  END IF;

  -- 8. 예·측(link_measurer_id) 검증
  IF p_link_measurer_id IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'LINK_MEASURER_REQUIRED';
  END IF;
  SELECT name INTO link_name FROM public.users WHERE id = p_link_measurer_id;
  IF link_name IS NULL THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'LINK_MEASURER_NOT_FOUND';
  END IF;
  -- 8-1. 예·측은 정정 후 예비조사자에 포함되어야 한다
  IF NOT p_participant_user_ids @> jsonb_build_array(p_link_measurer_id) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'LINK_MEASURER_NOT_IN_PARTICIPANTS';
  END IF;
  -- 8-2. 예·측은 실제 측정 인원(전체 기간)에 포함되어야 한다
  IF NOT (link_name = ANY(staff_names)) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'LINK_MEASURER_NOT_IN_STAFF';
  END IF;

  -- 9. V2 예비조사자 정정 (plan_origin manual, responsible = 예·측으로 정합)
  UPDATE public.preliminary_survey_v2_plans
  SET participant_user_ids = p_participant_user_ids,
      participant_names = p_participant_names,
      responsible_user_id = p_link_measurer_id,
      plan_origin = 'manual',
      updated_at = CURRENT_TIMESTAMP
  WHERE id = plan_row.id
  RETURNING * INTO plan_row;

  -- 10. 예·측 지정
  UPDATE public.measurement_target_business
  SET link_measurer_id = p_link_measurer_id,
      updated_at = CURRENT_TIMESTAMP
  WHERE id = p_target_id;

  -- 11. 감사기록 (변경 전 값은 위 갱신 전 스냅샷 사용)
  INSERT INTO public.preliminary_survey_exception_log (
    measurement_target_business_id, code,
    old_participant_user_ids, new_participant_user_ids,
    old_participant_names, new_participant_names,
    old_link_measurer_id, new_link_measurer_id,
    changed_by, reason
  ) VALUES (
    p_target_id, target_row.code,
    COALESCE(plan_row.participant_user_ids, '[]'::jsonb), p_participant_user_ids,
    COALESCE(plan_row.participant_names, '[]'::jsonb), p_participant_names,
    target_row.link_measurer_id, p_link_measurer_id,
    COALESCE(p_changed_by, 'admin'), btrim(p_reason)
  );

  RETURN plan_row;
END;
$$;

-- ---------- 3. 권한 ----------
REVOKE ALL ON FUNCTION public.admin_repair_preliminary_survey_connection(
  bigint, jsonb, jsonb, integer, text, text
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.admin_repair_preliminary_survey_connection(
  bigint, jsonb, jsonb, integer, text, text
) TO service_role;

NOTIFY pgrst, 'reload schema';
