-- Fixed-assignee reverse planner v1. Forward-only, additive, no backfill.
ALTER TABLE public.preliminary_survey_v2_measurement_assignments
  ADD COLUMN IF NOT EXISTS public_sample_code text;
ALTER TABLE public.preliminary_survey_v2_measurement_assignments
  DROP CONSTRAINT IF EXISTS preliminary_survey_v2_assignment_public_sample_code_check;
ALTER TABLE public.preliminary_survey_v2_measurement_assignments
  ADD CONSTRAINT preliminary_survey_v2_assignment_public_sample_code_check
  CHECK (public_sample_code IS NULL OR public_sample_code ~ '^(A+|B+|C+|D+|F+|G+)$');

-- survey_code는 앞으로 항상 users.survey_code의 단일 base snapshot으로 저장한다.
-- 기존 반복 code row는 일괄 backfill하지 않고, 해당 그룹이 Apply로 변경될 때만 base로 정규화된다.
CREATE OR REPLACE FUNCTION public.validate_preliminary_survey_v2_measurement_assignment()
RETURNS trigger
LANGUAGE plpgsql SET search_path = '' AS $$
DECLARE configured_survey_code text;
BEGIN
  SELECT upper(btrim(COALESCE(survey_code, ''))) INTO configured_survey_code
  FROM public.users
  WHERE id = NEW.assignee_user_id AND is_active IS NOT FALSE;
  IF configured_survey_code NOT IN ('A', 'B', 'C', 'D', 'F', 'G') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'MEASUREMENT_ASSIGNMENT_SURVEY_CODE_REQUIRED';
  END IF;
  NEW.survey_code := configured_survey_code;
  NEW.survey_code_source := 'users.survey_code';
  NEW.updated_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.preliminary_survey_v2_fixed_assignments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  measurement_target_business_id bigint NOT NULL REFERENCES public.measurement_target_business(id) ON DELETE CASCADE,
  measurement_date date NOT NULL,
  assignee_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  confirmed_by_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  confirmed_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  confirmation_path text NOT NULL CHECK (confirmation_path IN ('planner_ui', 'admin_override')),
  source_fingerprint text NOT NULL CHECK (btrim(source_fingerprint) <> ''),
  source_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(source_snapshot) = 'object'),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_preliminary_survey_v2_fixed_target_date UNIQUE (measurement_target_business_id, measurement_date)
);
CREATE INDEX IF NOT EXISTS idx_preliminary_survey_v2_fixed_date_assignee
  ON public.preliminary_survey_v2_fixed_assignments(measurement_date, assignee_user_id);
COMMENT ON TABLE public.preliminary_survey_v2_fixed_assignments IS
  '사용자가 실제 측정일별로 명시 확정한 고정 측정자. 기존 V2 assignment와 별도 authoritative source.';

CREATE TABLE IF NOT EXISTS public.preliminary_survey_v2_planner_audit (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  planner_run_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('APPLY', 'MANUAL_OVERRIDE')),
  target_id bigint NOT NULL REFERENCES public.measurement_target_business(id) ON DELETE RESTRICT,
  measurement_date date,
  before_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  after_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  decision text NOT NULL,
  mutation_intent text NOT NULL CHECK (mutation_intent IN ('KEEP_EXISTING', 'CREATE', 'REPLACE', 'NONE')),
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(warnings) = 'array'),
  override_reason text,
  source_fingerprint text NOT NULL,
  canonical_sha text NOT NULL,
  planner_version text NOT NULL,
  actor_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK ((event_type = 'MANUAL_OVERRIDE' AND btrim(COALESCE(override_reason, '')) <> '')
    OR (event_type = 'APPLY' AND override_reason IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_preliminary_survey_v2_planner_audit_run
  ON public.preliminary_survey_v2_planner_audit(planner_run_id, target_id);

ALTER TABLE public.preliminary_survey_v2_fixed_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preliminary_survey_v2_planner_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public.preliminary_survey_v2_fixed_assignments FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON TABLE public.preliminary_survey_v2_planner_audit FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON TABLE public.preliminary_survey_v2_fixed_assignments TO service_role;
GRANT SELECT ON TABLE public.preliminary_survey_v2_planner_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.preliminary_survey_v2_planner_audit_id_seq TO service_role;

CREATE OR REPLACE FUNCTION public.confirm_preliminary_survey_v2_fixed_assignment(
  p_target_id bigint, p_measurement_date date, p_assignee_user_id integer, p_actor_user_id integer,
  p_confirmation_path text, p_source_fingerprint text, p_source_snapshot jsonb
) RETURNS SETOF public.preliminary_survey_v2_fixed_assignments
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  target_row public.measurement_target_business;
  actor_allowed boolean;
  assignee_valid boolean;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM public.users WHERE id = p_actor_user_id AND is_active IS NOT FALSE
      AND (role = '관리자' OR is_preliminary_survey_manager IS TRUE)
  ) INTO actor_allowed;
  IF NOT actor_allowed THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'PLANNER_MANAGER_REQUIRED';
  END IF;
  IF p_confirmation_path NOT IN ('planner_ui', 'admin_override')
     OR btrim(COALESCE(p_source_fingerprint, '')) = ''
     OR jsonb_typeof(COALESCE(p_source_snapshot, '{}'::jsonb)) <> 'object' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_FIXED_ASSIGNMENT_PAYLOAD';
  END IF;

  SELECT * INTO target_row
  FROM public.measurement_target_business WHERE id = p_target_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'TARGET_NOT_FOUND';
  END IF;
  IF p_measurement_date >= DATE '2026-08-01' AND p_measurement_date < DATE '2026-09-01' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'TRANSITION_BOUNDARY_REVIEW_REQUIRED';
  END IF;
  IF p_measurement_date IS DISTINCT FROM target_row.measurement_date::date AND NOT EXISTS (
    SELECT 1
    FROM jsonb_array_elements(
      CASE WHEN jsonb_typeof(target_row.daily_staff) = 'array' THEN target_row.daily_staff ELSE '[]'::jsonb END
    ) day
    WHERE day->>'date' = p_measurement_date::text
  ) THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'FIXED_ASSIGNMENT_DATE_MISMATCH';
  END IF;
  SELECT EXISTS (
    SELECT 1 FROM public.users
    WHERE id = p_assignee_user_id AND is_active IS NOT FALSE AND job = '측정'
      AND upper(btrim(COALESCE(survey_code, ''))) IN ('A', 'B', 'C', 'D', 'F', 'G')
  ) INTO assignee_valid;
  IF NOT assignee_valid THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_FIXED_ASSIGNEE';
  END IF;

  PERFORM pg_advisory_xact_lock(hashtextextended(
    'fixed-assignment|' || p_target_id::text || '|' || p_measurement_date::text, 0
  ));
  RETURN QUERY
  INSERT INTO public.preliminary_survey_v2_fixed_assignments (
    measurement_target_business_id, measurement_date, assignee_user_id, confirmed_by_user_id,
    confirmed_at, confirmation_path, source_fingerprint, source_snapshot
  ) VALUES (
    p_target_id, p_measurement_date, p_assignee_user_id, p_actor_user_id, CURRENT_TIMESTAMP,
    p_confirmation_path, p_source_fingerprint, p_source_snapshot
  )
  ON CONFLICT (measurement_target_business_id, measurement_date) DO UPDATE SET
    assignee_user_id = EXCLUDED.assignee_user_id,
    confirmed_by_user_id = EXCLUDED.confirmed_by_user_id,
    confirmed_at = CURRENT_TIMESTAMP,
    confirmation_path = EXCLUDED.confirmation_path,
    source_fingerprint = EXCLUDED.source_fingerprint,
    source_snapshot = EXCLUDED.source_snapshot,
    updated_at = CURRENT_TIMESTAMP
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_preliminary_survey_v2_reverse_planner(
  p_planner_run_id uuid,
  p_source_fingerprint text,
  p_canonical_sha text,
  p_planner_version text,
  p_plans jsonb,
  p_assignments jsonb,
  p_actor_user_id integer,
  p_override_reason text DEFAULT NULL
) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  plan_item jsonb;
  assignment_item jsonb;
  target_row public.measurement_target_business;
  persisted_plan_id uuid;
  actor_role text;
  actor_manager boolean;
  affected_groups jsonb := '[]'::jsonb;
  applied_count integer := 0;
BEGIN
  SELECT role, (role = '관리자' OR is_preliminary_survey_manager IS TRUE)
  INTO actor_role, actor_manager
  FROM public.users
  WHERE id = p_actor_user_id AND is_active IS NOT FALSE;
  IF actor_manager IS NOT TRUE THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'PLANNER_MANAGER_REQUIRED';
  END IF;
  IF p_override_reason IS NOT NULL
     AND (actor_role <> '관리자' OR btrim(p_override_reason) = '') THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'ADMIN_OVERRIDE_REQUIRED';
  END IF;
  IF btrim(COALESCE(p_source_fingerprint, '')) = ''
     OR jsonb_typeof(p_plans) <> 'array'
     OR jsonb_typeof(p_assignments) <> 'array' THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_REVERSE_PLANNER_PAYLOAD';
  END IF;

  FOR plan_item IN
    SELECT value FROM jsonb_array_elements(p_plans)
    ORDER BY (value->>'target_id')::bigint
  LOOP
    IF plan_item->>'mutation' NOT IN ('KEEP_EXISTING', 'CREATE', 'REPLACE') THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_MUTATION_INTENT';
    END IF;
    IF p_override_reason IS NULL AND plan_item->>'decision' <> 'AUTO_ASSIGNED' THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'MANUAL_DECISION_NOT_APPLICABLE';
    END IF;

    SELECT * INTO target_row
    FROM public.measurement_target_business
    WHERE id = (plan_item->>'target_id')::bigint
    FOR UPDATE;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'TARGET_NOT_FOUND';
    END IF;
    IF target_row.measurement_date::date >= DATE '2026-08-01'
       AND target_row.measurement_date::date < DATE '2026-09-01'
       OR EXISTS (
         SELECT 1 FROM jsonb_array_elements(
           CASE WHEN jsonb_typeof(target_row.daily_staff) = 'array' THEN target_row.daily_staff ELSE '[]'::jsonb END
         ) day
         WHERE day->>'date' >= '2026-08-01' AND day->>'date' < '2026-09-01'
       ) THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'TRANSITION_BOUNDARY_REVIEW_REQUIRED';
    END IF;
    IF target_row.measurement_date::text IS DISTINCT FROM plan_item->>'source_measurement_date'
       OR COALESCE(target_row.measurer_id, -1)
          IS DISTINCT FROM COALESCE((plan_item->>'source_report_writer_id')::integer, -1)
       OR COALESCE(target_row.collaborators, '')
          IS DISTINCT FROM COALESCE(plan_item->>'source_collaborators', '')
       OR COALESCE(target_row.daily_staff, 'null'::jsonb)
          IS DISTINCT FROM COALESCE(plan_item->'source_daily_staff', 'null'::jsonb) THEN
      RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'SOURCE_CHANGED';
    END IF;
    IF EXISTS (
      SELECT 1 FROM jsonb_array_elements(p_assignments) item
      WHERE (item->>'target_id')::bigint = target_row.id
        AND NOT EXISTS (
          SELECT 1
          FROM public.preliminary_survey_v2_fixed_assignments fixed
          WHERE fixed.measurement_target_business_id = target_row.id
            AND fixed.measurement_date = (item->>'measurement_date')::date
            AND fixed.assignee_user_id = (item->>'assignee_user_id')::integer
        )
    ) THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'FIXED_ASSIGNEE_SOURCE_CHANGED';
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM jsonb_array_elements(p_assignments) item
      WHERE (item->>'target_id')::bigint = target_row.id
    ) THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'FIXED_ASSIGNEE_NOT_CONFIRMED';
    END IF;

    IF plan_item->>'mutation' <> 'KEEP_EXISTING' THEN
      INSERT INTO public.preliminary_survey_v2_plans (
        measurement_target_business_id, recommended_date, responsible_user_id,
        experienced_reviewer_id, participant_user_ids, participant_names, status,
        plan_origin, source_measurement_date, source_responsible_user_id,
        source_rule_type, survey_method, recommendation_reason, route_evidence, warnings
      ) VALUES (
        target_row.id,
        (plan_item->>'preliminary_date')::date,
        (plan_item->>'responsible_user_id')::integer,
        NULLIF(plan_item->>'reviewer_user_id', '')::integer,
        plan_item->'participant_user_ids',
        plan_item->'participant_names',
        'recommended',
        'automatic',
        target_row.measurement_date::date,
        target_row.measurer_id,
        plan_item->>'source_rule_type',
        plan_item->>'survey_method',
        jsonb_build_object(
          'plannerRunId', p_planner_run_id,
          'sourceFingerprint', p_source_fingerprint,
          'canonicalSha', p_canonical_sha,
          'plannerVersion', p_planner_version,
          'reason', plan_item->'reasons'
        ),
        COALESCE(plan_item->'route_evidence', '{}'::jsonb),
        COALESCE(plan_item->'warnings', '[]'::jsonb)
      )
      ON CONFLICT (measurement_target_business_id) DO UPDATE SET
        recommended_date = EXCLUDED.recommended_date,
        responsible_user_id = EXCLUDED.responsible_user_id,
        experienced_reviewer_id = EXCLUDED.experienced_reviewer_id,
        participant_user_ids = EXCLUDED.participant_user_ids,
        participant_names = EXCLUDED.participant_names,
        status = EXCLUDED.status,
        plan_origin = EXCLUDED.plan_origin,
        source_measurement_date = EXCLUDED.source_measurement_date,
        source_responsible_user_id = EXCLUDED.source_responsible_user_id,
        source_rule_type = EXCLUDED.source_rule_type,
        survey_method = EXCLUDED.survey_method,
        recommendation_reason = EXCLUDED.recommendation_reason,
        route_evidence = EXCLUDED.route_evidence,
        warnings = EXCLUDED.warnings,
        updated_at = CURRENT_TIMESTAMP
      RETURNING id INTO persisted_plan_id;

      FOR assignment_item IN
        SELECT value FROM jsonb_array_elements(p_assignments)
        WHERE (value->>'target_id')::bigint = target_row.id
        ORDER BY value->>'measurement_date'
      LOOP
        INSERT INTO public.preliminary_survey_v2_measurement_assignments (
          plan_id, measurement_date, assignee_user_id, survey_code,
          public_sample_code, assignment_reason
        ) VALUES (
          persisted_plan_id,
          (assignment_item->>'measurement_date')::date,
          (assignment_item->>'assignee_user_id')::integer,
          assignment_item->>'survey_code',
          assignment_item->>'public_sample_code',
          'fixed-assignee reverse planner'
        )
        ON CONFLICT (plan_id, measurement_date) DO UPDATE SET
          assignee_user_id = EXCLUDED.assignee_user_id,
          survey_code = EXCLUDED.survey_code,
          public_sample_code = EXCLUDED.public_sample_code,
          assignment_reason = EXCLUDED.assignment_reason,
          updated_at = CURRENT_TIMESTAMP;
        affected_groups := affected_groups || jsonb_build_array(jsonb_build_object(
          'date', assignment_item->>'measurement_date',
          'userId', assignment_item->>'assignee_user_id'
        ));
      END LOOP;
      applied_count := applied_count + 1;
    END IF;

    INSERT INTO public.preliminary_survey_v2_planner_audit (
      planner_run_id, event_type, target_id, measurement_date,
      before_snapshot, after_snapshot, decision, mutation_intent,
      warnings, override_reason, source_fingerprint, canonical_sha,
      planner_version, actor_user_id
    ) VALUES (
      p_planner_run_id,
      CASE WHEN p_override_reason IS NULL THEN 'APPLY' ELSE 'MANUAL_OVERRIDE' END,
      target_row.id,
      target_row.measurement_date::date,
      COALESCE(plan_item->'before_snapshot', '{}'::jsonb),
      plan_item,
      COALESCE(plan_item->>'decision', 'AUTO_ASSIGNED'),
      plan_item->>'mutation',
      COALESCE(plan_item->'warnings', '[]'::jsonb),
      p_override_reason,
      p_source_fingerprint,
      p_canonical_sha,
      p_planner_version,
      p_actor_user_id
    );
  END LOOP;

  WITH affected AS (
    SELECT DISTINCT
      (item->>'date')::date AS measurement_date,
      (item->>'userId')::integer AS assignee_user_id
    FROM jsonb_array_elements(affected_groups) item
  ), ranked AS (
    SELECT
      assignment.id,
      upper(btrim(base_user.survey_code)) AS base_code,
      row_number() OVER (
        PARTITION BY assignment.measurement_date, assignment.assignee_user_id
        ORDER BY target.code, target.id
      ) AS position
    FROM public.preliminary_survey_v2_measurement_assignments assignment
    JOIN public.users base_user ON base_user.id = assignment.assignee_user_id
    JOIN public.preliminary_survey_v2_plans plan ON plan.id = assignment.plan_id
    JOIN public.measurement_target_business target
      ON target.id = plan.measurement_target_business_id
    JOIN affected
      ON affected.measurement_date = assignment.measurement_date
     AND affected.assignee_user_id = assignment.assignee_user_id
  )
  UPDATE public.preliminary_survey_v2_measurement_assignments assignment
  SET public_sample_code = repeat(ranked.base_code, ranked.position::integer),
      updated_at = CURRENT_TIMESTAMP
  FROM ranked
  WHERE assignment.id = ranked.id;

  RETURN jsonb_build_object(
    'appliedCount', applied_count,
    'plannerRunId', p_planner_run_id
  );
END;
$$;

REVOKE ALL ON FUNCTION public.confirm_preliminary_survey_v2_fixed_assignment(
  bigint, date, integer, integer, text, text, jsonb
) FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.apply_preliminary_survey_v2_reverse_planner(
  uuid, text, text, text, jsonb, jsonb, integer, text
) FROM PUBLIC, anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.confirm_preliminary_survey_v2_fixed_assignment(
  bigint, date, integer, integer, text, text, jsonb
) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_preliminary_survey_v2_reverse_planner(
  uuid, text, text, text, jsonb, jsonb, integer, text
) TO service_role;

NOTIFY pgrst, 'reload schema';
