-- 예비조사 자동배정 V2. 기존 preliminary_survey 및 PR #9 legacy 테이블은 삭제/변경하지 않는다.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS is_preliminary_survey_experienced boolean NOT NULL DEFAULT false;

ALTER TABLE public.measurement_target_business
  ADD COLUMN IF NOT EXISTS preliminary_survey_rule_type text NOT NULL DEFAULT 'existing';

ALTER TABLE public.measurement_target_business
  DROP CONSTRAINT IF EXISTS measurement_target_business_preliminary_rule_type_v2_check;
ALTER TABLE public.measurement_target_business
  ADD CONSTRAINT measurement_target_business_preliminary_rule_type_v2_check
  CHECK (preliminary_survey_rule_type IN ('existing', 'general_new', 'other_org_new', 'unconfirmed_new'));

CREATE TABLE IF NOT EXISTS public.user_schedule_blocks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  start_date date NOT NULL,
  end_date date NOT NULL,
  block_type text NOT NULL,
  note text,
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date >= start_date)
);
CREATE INDEX IF NOT EXISTS idx_user_schedule_blocks_user_dates
  ON public.user_schedule_blocks(user_id, start_date, end_date);

CREATE TABLE IF NOT EXISTS public.preliminary_survey_v2_plans (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  measurement_target_business_id bigint NOT NULL UNIQUE
    REFERENCES public.measurement_target_business(id) ON DELETE CASCADE,
  recommended_date date,
  responsible_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  experienced_reviewer_id integer REFERENCES public.users(id) ON DELETE RESTRICT,
  participant_user_ids jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(participant_user_ids) = 'array'),
  participant_names jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(participant_names) = 'array'),
  status text NOT NULL CHECK (status IN ('recommended', 'manual_required')),
  plan_origin text NOT NULL DEFAULT 'automatic' CHECK (plan_origin IN ('automatic', 'manual')),
  source_measurement_date date NOT NULL,
  source_responsible_user_id integer NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  source_rule_type text NOT NULL,
  survey_method text NOT NULL,
  recommendation_reason jsonb NOT NULL DEFAULT '{}'::jsonb,
  route_evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  warnings jsonb NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(warnings) = 'array'),
  created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.preliminary_survey_v2_plans
  ADD COLUMN IF NOT EXISTS survey_method text;
UPDATE public.preliminary_survey_v2_plans
SET survey_method = CASE WHEN source_rule_type = 'new' THEN 'field' ELSE 'phone' END
WHERE survey_method IS NULL;
ALTER TABLE public.preliminary_survey_v2_plans
  ALTER COLUMN survey_method SET NOT NULL;
ALTER TABLE public.preliminary_survey_v2_plans
  DROP CONSTRAINT IF EXISTS preliminary_survey_v2_plans_survey_method_check;
ALTER TABLE public.preliminary_survey_v2_plans
  ADD CONSTRAINT preliminary_survey_v2_plans_survey_method_check
  CHECK (survey_method IN ('field', 'phone'));

COMMENT ON TABLE public.preliminary_survey_v2_plans IS
'V2 단일 최적안. recommendation_score를 사용하지 않고 구조화된 판단 근거를 저장한다.';
COMMENT ON COLUMN public.preliminary_survey_v2_plans.plan_origin IS
'자동추천 후 관리자가 날짜/조사자를 변경하면 manual';

CREATE INDEX IF NOT EXISTS idx_preliminary_survey_v2_date
  ON public.preliminary_survey_v2_plans(recommended_date, status);

DROP FUNCTION IF EXISTS public.persist_preliminary_survey_v2_plan(
  bigint, date, integer, integer, jsonb, jsonb, text, text, date, integer, text, jsonb, jsonb, jsonb
);

CREATE OR REPLACE FUNCTION public.persist_preliminary_survey_v2_plan(
  p_target_id bigint,
  p_recommended_date date,
  p_responsible_user_id integer,
  p_experienced_reviewer_id integer,
  p_participant_user_ids jsonb,
  p_participant_names jsonb,
  p_status text,
  p_plan_origin text,
  p_source_measurement_date date,
  p_source_responsible_user_id integer,
  p_source_rule_type text,
  p_survey_method text,
  p_recommendation_reason jsonb,
  p_route_evidence jsonb,
  p_warnings jsonb
) RETURNS SETOF public.preliminary_survey_v2_plans
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  target_row public.measurement_target_business;
  journal_is_new boolean;
  journal_rule_type text;
BEGIN
  IF p_status NOT IN ('recommended', 'manual_required') OR p_plan_origin NOT IN ('automatic', 'manual')
    OR p_survey_method NOT IN ('field', 'phone') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_V2_PLAN_PAYLOAD';
  END IF;
  SELECT * INTO target_row FROM public.measurement_target_business WHERE id = p_target_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'TARGET_NOT_FOUND'; END IF;
  IF target_row.measurement_date IS DISTINCT FROM p_source_measurement_date
    OR target_row.measurer_id IS DISTINCT FROM p_source_responsible_user_id THEN
    RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'V2_PLAN_SOURCE_CHANGED';
  END IF;
  SELECT EXISTS (
    SELECT 1
    FROM unnest(string_to_array(COALESCE(journal.note, ''), ',')) AS token(value)
    WHERE btrim(token.value) IN ('신규', '최초실시', '타기관 신규')
  ) INTO journal_is_new
  FROM public.measurement_journal AS journal
  WHERE journal.code = target_row.code
    AND journal.measurement_year = target_row.year
    AND btrim(journal.measurement_period) = btrim(target_row.period)
  ORDER BY journal.updated_at DESC NULLS LAST, journal.created_at DESC NULLS LAST, journal.id DESC
  LIMIT 1;
  journal_rule_type := CASE WHEN COALESCE(journal_is_new, false) THEN 'new' ELSE 'existing' END;
  IF p_source_rule_type IS DISTINCT FROM journal_rule_type THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'V2_CLASSIFICATION_SOURCE_MISMATCH';
  END IF;

  RETURN QUERY
  INSERT INTO public.preliminary_survey_v2_plans (
    measurement_target_business_id, recommended_date, responsible_user_id, experienced_reviewer_id,
    participant_user_ids, participant_names, status, plan_origin, source_measurement_date,
    source_responsible_user_id, source_rule_type, survey_method, recommendation_reason, route_evidence, warnings
  ) VALUES (
    p_target_id, p_recommended_date, p_responsible_user_id, p_experienced_reviewer_id,
    COALESCE(p_participant_user_ids, '[]'::jsonb), COALESCE(p_participant_names, '[]'::jsonb),
    p_status, p_plan_origin, p_source_measurement_date, p_source_responsible_user_id,
    p_source_rule_type, p_survey_method, COALESCE(p_recommendation_reason, '{}'::jsonb),
    COALESCE(p_route_evidence, '{}'::jsonb), COALESCE(p_warnings, '[]'::jsonb)
  ) ON CONFLICT (measurement_target_business_id) DO UPDATE SET
    recommended_date = EXCLUDED.recommended_date,
    responsible_user_id = EXCLUDED.responsible_user_id,
    experienced_reviewer_id = EXCLUDED.experienced_reviewer_id,
    participant_user_ids = EXCLUDED.participant_user_ids,
    participant_names = EXCLUDED.participant_names,
    status = EXCLUDED.status,
    plan_origin = EXCLUDED.plan_origin,
    source_measurement_date = EXCLUDED.source_measurement_date,
    source_responsible_user_id = EXCLUDED.source_responsible_user_id,
    source_rule_type = EXCLUDED.source_rule_type,
    survey_method = EXCLUDED.survey_method,
    recommendation_reason = EXCLUDED.recommendation_reason,
    route_evidence = EXCLUDED.route_evidence,
    warnings = EXCLUDED.warnings,
    updated_at = CURRENT_TIMESTAMP
  RETURNING *;
END;
$$;

REVOKE ALL ON TABLE public.preliminary_survey_v2_plans FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.preliminary_survey_v2_plans TO service_role;
REVOKE ALL ON FUNCTION public.persist_preliminary_survey_v2_plan(
  bigint, date, integer, integer, jsonb, jsonb, text, text, date, integer, text, text, jsonb, jsonb, jsonb
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.persist_preliminary_survey_v2_plan(
  bigint, date, integer, integer, jsonb, jsonb, text, text, date, integer, text, text, jsonb, jsonb, jsonb
) TO service_role;

NOTIFY pgrst, 'reload schema';
