-- 예비조사일·예비조사자 자동 추천 1차 최소 기능
-- 기존 preliminary_survey와 측정 일정/Google Calendar 컬럼은 변경하지 않는다.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS is_preliminary_survey_experienced BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS is_preliminary_survey_support_assignable BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.users
  DROP CONSTRAINT IF EXISTS users_preliminary_survey_support_requires_experience;
ALTER TABLE public.users
  ADD CONSTRAINT users_preliminary_survey_support_requires_experience
  CHECK (
    NOT is_preliminary_survey_support_assignable
    OR is_preliminary_survey_experienced
  );

ALTER TABLE public.measurement_target_business
  ADD COLUMN IF NOT EXISTS preliminary_survey_rule_type TEXT NOT NULL DEFAULT 'existing',
  ADD COLUMN IF NOT EXISTS requires_field_preliminary_survey BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.measurement_target_business
  DROP CONSTRAINT IF EXISTS measurement_target_business_preliminary_rule_type_check;
ALTER TABLE public.measurement_target_business
  ADD CONSTRAINT measurement_target_business_preliminary_rule_type_check
  CHECK (preliminary_survey_rule_type IN (
    'existing', 'general_new', 'other_org_new', 'unconfirmed_new'
  ));

ALTER TABLE public.measurement_target_business
  DROP CONSTRAINT IF EXISTS measurement_target_business_preliminary_rule_consistency;
ALTER TABLE public.measurement_target_business
  ADD CONSTRAINT measurement_target_business_preliminary_rule_consistency
  CHECK (
    requires_field_preliminary_survey =
      (preliminary_survey_rule_type IN ('general_new', 'other_org_new', 'unconfirmed_new'))
  );

CREATE TABLE IF NOT EXISTS public.user_schedule_blocks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  block_type TEXT NOT NULL CHECK (block_type IN (
    'education', 'leave', 'business_trip', 'meeting',
    'medical_checkup', 'personal', 'other'
  )),
  note TEXT,
  created_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT user_schedule_blocks_valid_range CHECK (end_date >= start_date)
);

CREATE INDEX IF NOT EXISTS idx_user_schedule_blocks_user_dates
  ON public.user_schedule_blocks(user_id, start_date, end_date);

CREATE TABLE IF NOT EXISTS public.preliminary_survey_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  measurement_target_business_id BIGINT NOT NULL
    REFERENCES public.measurement_target_business(id) ON DELETE CASCADE,
  responsible_user_id INTEGER NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  experienced_user_id INTEGER REFERENCES public.users(id) ON DELETE RESTRICT,
  visit_mode TEXT CHECK (visit_mode IN ('experienced_solo_visit', 'joint_field_visit')),
  recommended_date DATE,
  confirmed_date DATE,
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'recommended', 'confirmed', 'needs_review', 'cancelled')),
  source_measurer_id INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  source_measurement_date DATE,
  source_address TEXT,
  source_target_updated_at TIMESTAMPTZ NOT NULL,
  recommendation_reason JSONB NOT NULL DEFAULT '{}'::JSONB,
  recommendation_score INTEGER,
  warnings JSONB NOT NULL DEFAULT '[]'::JSONB
    CHECK (jsonb_typeof(warnings) = 'array'),
  alternatives JSONB NOT NULL DEFAULT '[]'::JSONB
    CHECK (jsonb_typeof(alternatives) = 'array'),
  review_reasons JSONB NOT NULL DEFAULT '[]'::JSONB
    CHECK (jsonb_typeof(review_reasons) = 'array'),
  holiday_verification_status TEXT NOT NULL DEFAULT 'verified'
    CHECK (holiday_verification_status IN ('verified', 'incomplete', 'admin_overridden')),
  holiday_verification_override_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  holiday_verification_override_at TIMESTAMPTZ,
  holiday_verification_override_reason TEXT,
  holiday_calendar_status_snapshot JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  confirmed_by INTEGER REFERENCES public.users(id) ON DELETE SET NULL,
  confirmed_at TIMESTAMPTZ,
  row_version BIGINT NOT NULL DEFAULT 1 CHECK (row_version > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT preliminary_survey_plans_distinct_participants
    CHECK (experienced_user_id IS NULL OR experienced_user_id <> responsible_user_id),
  CONSTRAINT preliminary_survey_plans_status_payload
    CHECK (
      (
        status = 'pending'
        AND recommended_date IS NULL
        AND confirmed_date IS NULL
        AND visit_mode IS NULL
      )
      OR (
        status IN ('recommended', 'needs_review')
        AND recommended_date IS NOT NULL
        AND visit_mode IS NOT NULL
      )
      OR (
        status = 'confirmed'
        AND recommended_date IS NOT NULL
        AND confirmed_date IS NOT NULL
        AND visit_mode IS NOT NULL
        AND confirmed_at IS NOT NULL
      )
      OR status = 'cancelled'
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_preliminary_survey_plans_one_active
  ON public.preliminary_survey_plans(measurement_target_business_id)
  WHERE status IN ('pending', 'recommended', 'confirmed', 'needs_review');

CREATE INDEX IF NOT EXISTS idx_preliminary_survey_plans_workload
  ON public.preliminary_survey_plans(experienced_user_id, recommended_date, status)
  WHERE visit_mode = 'joint_field_visit'
    AND status IN ('recommended', 'confirmed');

CREATE OR REPLACE FUNCTION public.touch_preliminary_survey_mvp_row()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := CURRENT_TIMESTAMP;
  IF TG_TABLE_NAME = 'preliminary_survey_plans' THEN
    NEW.row_version := OLD.row_version + 1;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_preliminary_survey_plans
  ON public.preliminary_survey_plans;
CREATE TRIGGER trg_touch_preliminary_survey_plans
BEFORE UPDATE ON public.preliminary_survey_plans
FOR EACH ROW EXECUTE FUNCTION public.touch_preliminary_survey_mvp_row();

DROP TRIGGER IF EXISTS trg_touch_user_schedule_blocks
  ON public.user_schedule_blocks;
CREATE TRIGGER trg_touch_user_schedule_blocks
BEFORE UPDATE ON public.user_schedule_blocks
FOR EACH ROW EXECUTE FUNCTION public.touch_preliminary_survey_mvp_row();

CREATE OR REPLACE FUNCTION public.persist_preliminary_survey_recommendation(
  p_target_id BIGINT,
  p_expected_target_updated_at TIMESTAMPTZ,
  p_status TEXT,
  p_responsible_user_id INTEGER,
  p_experienced_user_id INTEGER,
  p_visit_mode TEXT,
  p_recommended_date DATE,
  p_source_measurer_id INTEGER,
  p_source_measurement_date DATE,
  p_source_address TEXT,
  p_recommendation_reason JSONB,
  p_recommendation_score INTEGER,
  p_warnings JSONB,
  p_alternatives JSONB,
  p_actor_user_id INTEGER
)
RETURNS SETOF public.preliminary_survey_plans
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  target_updated_at TIMESTAMPTZ;
  active_plan public.preliminary_survey_plans;
BEGIN
  IF p_status NOT IN ('pending', 'recommended') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'INVALID_PLAN_STATUS';
  END IF;

  SELECT updated_at INTO target_updated_at
  FROM public.measurement_target_business
  WHERE id = p_target_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'TARGET_NOT_FOUND';
  END IF;
  IF target_updated_at IS DISTINCT FROM p_expected_target_updated_at THEN
    RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'PLAN_SOURCE_CHANGED';
  END IF;

  SELECT * INTO active_plan
  FROM public.preliminary_survey_plans
  WHERE measurement_target_business_id = p_target_id
    AND status IN ('pending', 'recommended', 'confirmed', 'needs_review')
  FOR UPDATE;

  IF FOUND AND active_plan.status = 'confirmed' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'CONFIRMED_PLAN_REQUIRES_CANCEL';
  END IF;

  IF FOUND THEN
    RETURN QUERY
    UPDATE public.preliminary_survey_plans
    SET
      responsible_user_id = p_responsible_user_id,
      experienced_user_id = p_experienced_user_id,
      visit_mode = p_visit_mode,
      recommended_date = p_recommended_date,
      confirmed_date = NULL,
      status = p_status,
      source_measurer_id = p_source_measurer_id,
      source_measurement_date = p_source_measurement_date,
      source_address = p_source_address,
      source_target_updated_at = p_expected_target_updated_at,
      recommendation_reason = COALESCE(p_recommendation_reason, '{}'::JSONB),
      recommendation_score = p_recommendation_score,
      warnings = COALESCE(p_warnings, '[]'::JSONB),
      alternatives = COALESCE(p_alternatives, '[]'::JSONB),
      review_reasons = '[]'::JSONB,
      holiday_verification_status = CASE
        WHEN COALESCE(p_warnings, '[]'::JSONB) @> '["HOLIDAY_DATA_REVIEW_REQUIRED"]'::JSONB
          THEN 'incomplete'
        ELSE 'verified'
      END,
      holiday_verification_override_by = NULL,
      holiday_verification_override_at = NULL,
      holiday_verification_override_reason = NULL,
      holiday_calendar_status_snapshot = JSONB_BUILD_OBJECT(
        'reviewedYearFrom', 2025,
        'reviewedYearTo', 2027,
        'source', 'application_snapshot',
        'status', CASE
          WHEN COALESCE(p_warnings, '[]'::JSONB) @> '["HOLIDAY_DATA_REVIEW_REQUIRED"]'::JSONB
            THEN 'incomplete'
          ELSE 'verified'
        END
      ),
      confirmed_by = NULL,
      confirmed_at = NULL
    WHERE id = active_plan.id
    RETURNING *;
  ELSE
    RETURN QUERY
    INSERT INTO public.preliminary_survey_plans (
      measurement_target_business_id,
      responsible_user_id,
      experienced_user_id,
      visit_mode,
      recommended_date,
      status,
      source_measurer_id,
      source_measurement_date,
      source_address,
      source_target_updated_at,
      recommendation_reason,
      recommendation_score,
      warnings,
      alternatives,
      holiday_verification_status,
      holiday_calendar_status_snapshot,
      created_by
    )
    VALUES (
      p_target_id,
      p_responsible_user_id,
      p_experienced_user_id,
      p_visit_mode,
      p_recommended_date,
      p_status,
      p_source_measurer_id,
      p_source_measurement_date,
      p_source_address,
      p_expected_target_updated_at,
      COALESCE(p_recommendation_reason, '{}'::JSONB),
      p_recommendation_score,
      COALESCE(p_warnings, '[]'::JSONB),
      COALESCE(p_alternatives, '[]'::JSONB),
      CASE
        WHEN COALESCE(p_warnings, '[]'::JSONB) @> '["HOLIDAY_DATA_REVIEW_REQUIRED"]'::JSONB
          THEN 'incomplete'
        ELSE 'verified'
      END,
      JSONB_BUILD_OBJECT(
        'reviewedYearFrom', 2025,
        'reviewedYearTo', 2027,
        'source', 'application_snapshot',
        'status', CASE
          WHEN COALESCE(p_warnings, '[]'::JSONB) @> '["HOLIDAY_DATA_REVIEW_REQUIRED"]'::JSONB
            THEN 'incomplete'
          ELSE 'verified'
        END
      ),
      p_actor_user_id
    )
    RETURNING *;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.confirm_preliminary_survey_plan(
  p_plan_id UUID,
  p_expected_row_version BIGINT,
  p_confirmed_date DATE,
  p_actor_user_id INTEGER,
  p_holiday_override_reason TEXT
)
RETURNS SETOF public.preliminary_survey_plans
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  plan_target_id BIGINT;
  target_updated_at TIMESTAMPTZ;
  selected_plan public.preliminary_survey_plans;
BEGIN
  SELECT measurement_target_business_id INTO plan_target_id
  FROM public.preliminary_survey_plans
  WHERE id = p_plan_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0002', MESSAGE = 'PLAN_NOT_FOUND';
  END IF;

  SELECT updated_at INTO target_updated_at
  FROM public.measurement_target_business
  WHERE id = plan_target_id
  FOR SHARE;

  SELECT * INTO selected_plan
  FROM public.preliminary_survey_plans
  WHERE id = p_plan_id
  FOR UPDATE;

  IF selected_plan.row_version <> p_expected_row_version THEN
    RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'PLAN_VERSION_CONFLICT';
  END IF;
  IF selected_plan.status <> 'recommended' THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'PLAN_NOT_RECOMMENDED';
  END IF;
  IF selected_plan.source_target_updated_at IS DISTINCT FROM target_updated_at THEN
    RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'PLAN_SOURCE_CHANGED';
  END IF;

  PERFORM 1
  FROM public.users
  WHERE id = selected_plan.responsible_user_id
    AND is_active IS TRUE
    AND job = '측정'
    AND (
      selected_plan.visit_mode <> 'experienced_solo_visit'
      OR is_preliminary_survey_experienced IS TRUE
    )
  FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'RESPONSIBLE_USER_UNAVAILABLE';
  END IF;

  IF selected_plan.visit_mode = 'joint_field_visit' THEN
    PERFORM 1
    FROM public.users
    WHERE id = selected_plan.experienced_user_id
      AND is_active IS TRUE
      AND job = '측정'
      AND is_preliminary_survey_experienced IS TRUE
      AND is_preliminary_survey_support_assignable IS TRUE
    FOR SHARE;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'EXPERIENCED_USER_UNAVAILABLE';
    END IF;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.user_schedule_blocks
    WHERE user_id IN (
      selected_plan.responsible_user_id,
      selected_plan.experienced_user_id
    )
      AND start_date <= p_confirmed_date
      AND end_date >= p_confirmed_date
  ) THEN
    RAISE EXCEPTION USING ERRCODE = 'P0001', MESSAGE = 'USER_SCHEDULE_BLOCK_CONFLICT';
  END IF;

  IF selected_plan.holiday_verification_status = 'incomplete' THEN
    PERFORM 1
    FROM public.users
    WHERE id = p_actor_user_id
      AND role = '관리자'
      AND is_active IS TRUE
    FOR SHARE;
    IF NOT FOUND THEN
      RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'HOLIDAY_OVERRIDE_ADMIN_REQUIRED';
    END IF;
    IF NULLIF(BTRIM(p_holiday_override_reason), '') IS NULL THEN
      RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'HOLIDAY_OVERRIDE_REASON_REQUIRED';
    END IF;
  END IF;

  RETURN QUERY
  UPDATE public.preliminary_survey_plans
  SET
    status = 'confirmed',
    confirmed_date = p_confirmed_date,
    confirmed_by = p_actor_user_id,
    confirmed_at = CURRENT_TIMESTAMP,
    holiday_verification_status = CASE
      WHEN holiday_verification_status = 'incomplete' THEN 'admin_overridden'
      ELSE holiday_verification_status
    END,
    holiday_verification_override_by = CASE
      WHEN holiday_verification_status = 'incomplete' THEN p_actor_user_id
      ELSE holiday_verification_override_by
    END,
    holiday_verification_override_at = CASE
      WHEN holiday_verification_status = 'incomplete' THEN CURRENT_TIMESTAMP
      ELSE holiday_verification_override_at
    END,
    holiday_verification_override_reason = CASE
      WHEN holiday_verification_status = 'incomplete'
        THEN BTRIM(p_holiday_override_reason)
      ELSE holiday_verification_override_reason
    END,
    review_reasons = '[]'::JSONB
  WHERE id = p_plan_id
  RETURNING *;
END;
$$;

CREATE OR REPLACE FUNCTION public.cancel_preliminary_survey_plan(
  p_plan_id UUID,
  p_expected_row_version BIGINT
)
RETURNS SETOF public.preliminary_survey_plans
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN QUERY
  UPDATE public.preliminary_survey_plans
  SET status = 'cancelled'
  WHERE id = p_plan_id
    AND row_version = p_expected_row_version
    AND status IN ('pending', 'recommended', 'confirmed', 'needs_review')
  RETURNING *;

  IF NOT FOUND THEN
    RAISE EXCEPTION USING ERRCODE = '40001', MESSAGE = 'PLAN_VERSION_CONFLICT';
  END IF;
END;
$$;

ALTER TABLE public.preliminary_survey_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_schedule_blocks ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.preliminary_survey_plans FROM PUBLIC, anon, authenticated;
REVOKE ALL ON TABLE public.user_schedule_blocks FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE public.preliminary_survey_plans TO service_role;
GRANT ALL ON TABLE public.user_schedule_blocks TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.user_schedule_blocks_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.persist_preliminary_survey_recommendation(
  BIGINT, TIMESTAMPTZ, TEXT, INTEGER, INTEGER, TEXT, DATE, INTEGER, DATE,
  TEXT, JSONB, INTEGER, JSONB, JSONB, INTEGER
) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.confirm_preliminary_survey_plan(UUID, BIGINT, DATE, INTEGER, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.cancel_preliminary_survey_plan(UUID, BIGINT) FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.persist_preliminary_survey_recommendation(
  BIGINT, TIMESTAMPTZ, TEXT, INTEGER, INTEGER, TEXT, DATE, INTEGER, DATE,
  TEXT, JSONB, INTEGER, JSONB, JSONB, INTEGER
) TO service_role;
GRANT EXECUTE ON FUNCTION public.confirm_preliminary_survey_plan(UUID, BIGINT, DATE, INTEGER, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.cancel_preliminary_survey_plan(UUID, BIGINT) TO service_role;

UPDATE public.users
SET
  is_preliminary_survey_experienced = name IN ('이태환', '한기문', '이주형'),
  is_preliminary_survey_support_assignable = name IN ('이태환', '한기문', '이주형')
WHERE name IN ('이태환', '한기문', '이주형', '강종구', '고유빈', '김민영', '배윤민');

NOTIFY pgrst, 'reload schema';
