-- The address resolver has long treated these master tables as authoritative,
-- but their original DDL was not present in the checked-in migration chain.

CREATE TABLE IF NOT EXISTS public.labor_offices (
  office_code text PRIMARY KEY,
  current_official_name text,
  current_short_name text,
  jurisdiction_reference text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.labor_office_aliases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_code text NOT NULL REFERENCES public.labor_offices(office_code) ON DELETE CASCADE,
  business_office_name text,
  document_office_name text,
  mapping_note text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_labor_office_aliases_office_code
  ON public.labor_office_aliases(office_code);
